"""add routing_configs

Revision ID: 0a5746722fe4
Revises: b84eb3d51464
Create Date: 2026-02-28 00:36:38.317412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a5746722fe4'
down_revision: Union[str, Sequence[str], None] = 'b84eb3d51464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routing_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('yaml_content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routing_configs')
    # ### end Alembic commands ###
